name: "Post PR Comment"
description: "Posts a comment to a pull request with the deployment URL"

inputs:
  github-token:
    description: "GitHub token for authentication"
    required: true
  deployment-url:
    description: "The deployment URL to post in the comment"
    required: true
  pr-number:
    description: "The pull request number to comment on"
    required: true

runs:
  using: "composite"
  steps:
    - name: Post Comment
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const deploymentUrl = process.env.deployment_url.trim();
          const prNumber = process.env.pr_number;
          const commentBody = `✨ Preview available: [${deploymentUrl}](${deploymentUrl})`;

          // Create a comment on the PR
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: commentBody
          });
      env:
        deployment_url: ${{ inputs.deployment-url }}
        pr_number: ${{ inputs.pr-number }}
