name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Select the release type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      is_prerelease:
        description: "Create a pre-release"
        required: true
        type: boolean
        default: true
      is_draft:
        description: "Mark as a draft"
        required: true
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Downloads also the tags
          persist-credentials: false

      - name: Get latest tag
        id: get-latest-tag
        run: |
          # Verify if there are any tags in the repository
          if [ "$(git tag)" = "" ]; then
            echo "No tags found. Defaulting to v0.0.0"
            echo "latest_tag=v0.0.0" >> $GITHUB_ENV
          else
            # Get the latest tag based on chronological order
            latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo "Latest tag: $latest_tag"
            echo "latest_tag=$latest_tag" >> $GITHUB_ENV
          fi

      - name: Calculate next tag
        id: calculate-next-tag
        run: |
          # Extract the latest tag, stripping the 'v' prefix if it exists
          latest_tag="${{ env.latest_tag }}"
          latest_version="${latest_tag#v}" # Strips 'v' if present

          # Split the version into major, minor, and patch components
          IFS='.' read -ra PARTS <<< "$latest_version"
          major=${PARTS[0]:-0}
          minor=${PARTS[1]:-0}
          patch=${PARTS[2]:-0}

          # Determine release type
          release_type="${{ github.event.inputs.release_type }}"
          case $release_type in
            patch)
              patch=$((patch + 1))
              ;;
            minor)
              minor=$((minor + 1))
              patch=0
              ;;
            major)
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            *)
              echo "Invalid release type: $release_type"
              exit 1
              ;;
          esac

          # Generate the next tag
          next_tag="v$major.$minor.$patch"

          echo "Next tag: $next_tag"
          echo "next_tag=$next_tag" >> $GITHUB_ENV

      - name: Generate Release Body
        id: generate-release-body
        run: |
          # Check if this is the first release (no previous tags)
          if [ "${{ env.latest_tag }}" = "v0.0.0" ]; then
            echo "No previous tags found. Generating changelog for all commits."
            changelog=$(git log --pretty=format:"- %h %s" --no-merges)
          else
            echo "Generating changelog from the latest tag to current ref."
            changelog=$(git log "${{ env.latest_tag }}".."${{ github.ref_name }}" --pretty=format:"- %h %s" --no-merges)
          fi

          # Escape special characters in the changelog for JSON
          changelog=$(echo "$changelog" | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g' | sed "s/'/\\'/g")

          # Format the release body
          body="## Changes in ${{ env.next_tag }}\\n\\n$changelog"
          echo "Generated release body:"
          echo "$body"

          # Write the sanitized release body to $GITHUB_ENV
          echo "release_body=$body" >> $GITHUB_ENV

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Define if the release is a pre-release
          is_prerelease=${{ github.event.inputs.is_prerelease }}
          is_draft=${{ github.event.inputs.is_draft }}

          # Create the release using the GitHub API
          response=$(curl -s -o response.json -w "%{http_code}" \
          -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d @- << EOF
          {
            "tag_name": "${{ env.next_tag }}",
            "target_commitish": "main",
            "name": "Release ${{ env.next_tag }}",
            "body": "${{ env.release_body }}",
            "draft": $is_draft,
            "prerelease": $is_prerelease
          }
          EOF
          )

          # Check if the request was successful
          if [ "$response" -ne 201 ]; then
            echo "Failed to create release. Response code: $response"
            echo "Response body:"
            cat response.json
            exit 1
          fi

          echo "Release created successfully!"

      - name: Output Release Info
        run: |
          echo "Release created with tag ${{ env.next_tag }}"

      - name: Trigger Release Event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Determine the event type based on whether it's a pre-release or a release or draft
          if [ "${{ github.event.inputs.is_prerelease }}" = "true" ]; then
            if [ "${{ github.event.inputs.is_draft }}" = "true" ]; then
              event_type="draft_prerelease_created"
            else
              event_type="prerelease_created"
            fi
          else
            if [ "${{ github.event.inputs.is_draft }}" = "true" ]; then
              event_type="draft_release_created"
            else
              event_type="release_created"
            fi
          fi

          echo "Triggering repository_dispatch event: $event_type"

          response=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d @- << EOF
          {
            "event_type": "$event_type",
            "client_payload": {
              "ref": "${{ github.ref }}"
            }
          }
          EOF
          )

          if [ "$response" -ne 204 ]; then
            echo "Failed to dispatch release event. HTTP response code: $response"
            echo "Response body:"
            cat response.json
            exit 1
          else
            echo "Release event dispatched successfully!"
          fi