name: Deploy Pre-Release to Staging

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write 

jobs:
  Deploy-Staging:
    name: Deploy to Staging
    if: (github.event.release.prerelease == true && github.event.release.draft == false)
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Staging
        uses: ./.github/actions/build-and-deploy
        with:
          environment: 'Staging'
          is_preview: ${{ github.event.release.draft == true }}
          ref: ${{ github.ref }}
          notify_slack: ${{ vars.ENABLE_SLACK_NOTIFICATIONS == 'true' }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}