name: Deploy Release to Production

on:
  release:
    types:
      - released

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
  
jobs:
  Deploy-Production:
    if: (github.event.release.prerelease == false && github.event.release.draft == false) || github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      response=$(curl -s -o response.json -w "%{http_code}" \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $GITHUB_TOKEN" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/create-deployment.yml/dispatches \
        -d @- << EOF
      {
        "ref": "${{ github.ref }}",
        "inputs": {
          "environment": "Production", 
          "is_preview": "false" 
        }
      }
      EOF
      )

      if [ "$response" -ne 204 ]; then
        echo "Failed to dispatch release event. HTTP response code: $response"
        echo "Response body:"
        cat response.json
        exit 1
      else
        echo "Release event dispatched successfully!"
      fi