name: Merge Pull Request

on:
  pull_request:
    types:
      - closed

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_TEAM: ${{ vars.VERCEL_TEAM }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Development:
    if: github.event.pull_request.merged == true # Ensure the job only runs if the PR is merged
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - run: npm install
      - run: npm run build

      - name: Deploy Project Artifacts to Vercel
        run: npx vercel deploy --prod --token=$VERCEL_TOKEN

