name: Deploy PR Changes

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "!.github/**"
      - "!**/*.md"
      - "!.nvmrc"
      - "!.gitignore"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  Deploy-PR-Changes:
    name: Deploy PR Changes
    environment: Preview-Development
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: ./.github/actions/build-and-deploy
        with:
          environment: "Development"
          is_preview: true
          notify_slack: true
          post_pr_comment: true
          pr_number: ${{ github.event.pull_request.number }}
          ref: ${{ github.event.pull_request.head.ref }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel_id: ${{ secrets.SLACK_PREVIEW_CHANNEL_ID }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          vercel_team: ${{ vars.VERCEL_TEAM }}
