name: Deploy to Development

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write
  actions: write       # Allows access to trigger actions
  
jobs:
  Deploy-Development:
    if: github.event.pull_request.merged == true # Ensure the job only runs if the PR is merged
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - name: Trigger Release Event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/create-deployment.yml/dispatches \
            -d @- << EOF
          {
            "ref": "${{ github.ref }}",
            "inputs": {
              "environment": "Development", 
              "is_preview": "false" 
            }
          }
          EOF
          )

          if [ "$response" -ne 204 ]; then
            echo "Failed to dispatch release event. HTTP response code: $response"
            echo "Response body:"
            cat response.json
            exit 1
          else
            echo "Release event dispatched successfully!"
          fi

