name: Deploy to Preview-Development

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read           
  pull-requests: write 

jobs:
  Preview-Development:
    name: Deploy to Development (Preview) 
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_TEAM: ${{ vars.VERCEL_TEAM }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DEV_PROJECT_ID }}
      CI: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Project to Vercel
        id: deploy
        run: |
          # DEPLOY_URL=$(npx vercel deploy --scope $VERCEL_TEAM --token=$VERCEL_TOKEN)
          DEPLOY_URL=$(npx vercel deploy --token=$VERCEL_TOKEN)
          echo "deployment_url=$DEPLOY_URL" >> $GITHUB_ENV
          echo "Vercel Deployment URL: $DEPLOY_URL"

      - name: Post Vercel Deployment URL to PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deploymentUrl = process.env.deployment_url.trim();
            const prNumber = context.payload.pull_request.number;
            const commentBody = `✨ Preview available: [${deploymentUrl}](${deploymentUrl})`;

            // Create a comment on the PR
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody
            });
