name: Deploy to Development

on:
  pull_request:
    types:
      - closed

jobs:
  Deploy-Development:
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_TEAM: ${{ vars.VERCEL_TEAM }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DEV_PROJECT_ID }}
    if: github.event.pull_request.merged == true # Ensure the job only runs if the PR is merged
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Pull Vercel Environment
        run: npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build Project Artifacts
        run: npx vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy Project Artifacts to Vercel
        run: npx vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

