name: Deploy Draft Pre-Release to Preview-Staging

on:
  repository_dispatch:
    types:
      - draft_prerelease_created

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_TEAM: ${{ vars.VERCEL_TEAM }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PREVIEW_STAGING_PROJECT_ID }}
  
jobs:
  Deploy-Preview-Staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - run: npm install
      - run: npm test
      
      - name: Pull Vercel Environment
        run: npx vercel pull --yes --environment=preview --token=$VERCEL_TOKEN

      - name: Build Project Artifacts
        run: npx vercel build --token=$VERCEL_TOKEN

      - name: Deploy to Vercel
        run: npx vercel deploy --prebuilt --token=$VERCEL_TOKEN