name: Deploy Pre-Release to Staging

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: write  

jobs:
  Deploy-Staging:
    if: (github.event.release.prerelease == true && github.event.release.draft == false) || github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Trigger Release Event
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          response=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $PAT" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/create-deployment.yml/dispatches \
            -d @- << EOF
          {
            "ref": "${{ github.ref }}",
            "inputs": {
              "environment": "Staging", 
              "is_preview": "false" 
            }
          }
          EOF
          )

          if [ "$response" -ne 204 ]; then
            echo "Failed to dispatch release event. HTTP response code: $response"
            echo "Response body:"
            cat response.json
            exit 1
          else
            echo "Release event dispatched successfully!"
          fi