name: Deploy Pre-Release to Staging

on:
  release:
    types:
      - published  # Triggers when a pre-release or full release is published
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_TEAM: ${{ vars.VERCEL_TEAM }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
jobs:
  Deploy-Staging:
    if: github.event.release.prerelease == true && github.event.release.draft == false
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - run: npm install
      - run: npm test
      
      - name: Pull Vercel Environment
        run: npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Build Project Artifacts
        run: npx vercel build --prod --token=$VERCEL_TOKEN

      - name: Deploy to Vercel
        run: npx vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN