name: Deploy Pre-Release to Staging

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

jobs:
  Deploy-Staging:
    name: Deploy to Staging
    if: (github.event.release.prerelease == true && github.event.release.draft == false) || github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Deploy
        uses: ./.github/actions/build-and-deploy
        with:
          environment: "Staging"
          is_preview: false
          notify_slack: true
          post_pr_comment: false
          ref: ${{ github.ref }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_STAGING_PROJECT_ID }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          vercel_team: ${{ vars.VERCEL_TEAM }}
