name: PR merged to Development

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

permissions:
  contents: read
  actions: write

jobs:
  Deploy-Development:
    if: github.event.pull_request.merged == true # Ensure the job only runs if the PR is merged
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy
        uses: ./.github/actions/build-and-deploy
        with:
          environment: "Development"
          is_preview: false
          notify_slack: ${{ env.ENABLE_SLACK_NOTIFICATIONS == 'true' }}
          post_pr_comment: false
          ref: ${{ github.ref }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          vercel_team: ${{ vars.VERCEL_TEAM }}
