name: PR merged to Development

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

permissions:
  contents: read
  actions: write

jobs:
  Deploy-Development:
    if: github.event.pull_request.merged == true # Ensure the job only runs if the PR is merged
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - name: Trigger Deployment Event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          response=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/trigger-deployment.yml/dispatches \
            -d @- << EOF
          {
            "ref": "${{ github.ref }}",
            "inputs": {
              "environment": "Development",
              "is_preview": "false"
            }
          }
          EOF
          )

          if [ "$response" -ne 204 ]; then
            echo "Failed to dispatch deployment event. HTTP response code: $response"
            echo "Response body:"
            cat response.json
            exit 1
          else
            echo "Deployment event dispatched successfully!"
          fi
