name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    push:
      branches:
        - main


env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_TEAM: ${{ vars.VERCEL_TEAM }}

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run linter
        run: npm run lint --quiet

      - name: Run build
        run: npm run build

      - name: Pull Vercel Environment Information
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
          else
            vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          fi

      - name: Build Project Artifacts
        run: vercel build --token=$VERCEL_TOKEN
        
      - name: Deploy Project Artifacts to Vercel
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            vercel deploy --prod --prebuilt --token=$VERCEL_TOKEN
          else
            vercel deploy --prebuilt --token=$VERCEL_TOKEN
          fi
