name: Deploy Release to Production

on:
  release:
    types:
      - released

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write       # Allows access to repo contents

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_TEAM: ${{ vars.VERCEL_TEAM }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
jobs:
  Download-Assets:
    runs-on: ubuntu-latest
    outputs:
      assets-dir: ${{ steps.output-assets.outputs.assets-dir }}
    steps:
      - name: Create a directory for assets
        id: output-assets
        run: |
          mkdir -p release-assets
          echo "assets-dir=release-assets" >> $GITHUB_ENV

      - name: Download release assets
        uses: actions/download-artifact@v4
        with:
          name: app-build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ steps.output-assets.outputs.assets-dir }}

      - name: List downloaded assets
        run: ls -R ${{ steps.output-assets.outputs.assets-dir }}

  Deploy-Production:
    needs: download-assets
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Deploy to Vercel
        run: |
          echo "Deploying with assets from pre-release..."
          vercel deploy --prod --token=$VERCEL_TOKEN --files=$GITHUB_WORKSPACE/$assets-dir