name: Trigger Vercel Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        type: choice
        options:
          - Development
          - Staging
          - Production
        default: Development
      is_preview:
        description: "Create a preview"
        required: true
        type: boolean
        default: true
      notify_slack:
        description: "Send Slack notification"
        required: false
        type: boolean
        default: true
      post_pr_comment:
        description: "Post deployment URL as PR comment"
        required: false
        type: boolean
        default: false
      pr_number:
        description: "Pull Request number to comment on"
        required: false
        type: number

concurrency:
  group: ${{ github.workflow }}-${{ inputs.environment }} ${{ inputs.is_preview == 'true' && '(Preview)' || '' }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: write

jobs:
  Trigger-Deployment:
    name: Deploy to ${{ github.event.inputs.environment }} ${{ github.event.inputs.is_preview == 'true' && '(Preview)' || '' }}
    environment: ${{ github.event.inputs.is_preview == 'true' && format('Preview-{0}', github.event.inputs.environment) || github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build and Deploy
        uses: ./.github/actions/build-and-deploy
        with:
          environment: ${{ github.event.inputs.environment }}
          is_preview: ${{ github.event.inputs.is_preview }}
          notify_slack: ${{ github.event.inputs.notify_slack }}
          post_pr_comment: ${{ github.event.inputs.post_pr_comment }}
          pr_number: ${{ github.event.inputs.pr_number }}
          ref: ${{ github.ref }}
          vercel_org_id: ${{ secrets.VERCEL_ORG_ID }}
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          slack_channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          vercel_team: ${{ vars.VERCEL_TEAM }}
