name: Trigger Vercel Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        type: choice
        options:
          - Development
          - Staging
          - Production
        default: Development
      is_preview:
        description: "Create a preview"
        required: true
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }} ${{ github.event.inputs.is_preview == 'true' && '(Preview)' || '' }}
  cancel-in-progress: false

jobs:
  Trigger-Deployment:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.is_preview == 'false' && github.event.inputs.environment || null }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_TEAM: ${{ vars.VERCEL_TEAM }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Downloads also the tags
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - run: npm install
      - run: npm test

      - name: Set Vercel Project ID
        run: |
          case "${{ github.event.inputs.environment }}" in
            Development)
              echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_DEV_PROJECT_ID }}" >> $GITHUB_ENV
              ;;
            Staging)
              echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_STAGING_PROJECT_ID }}" >> $GITHUB_ENV
              ;;
            Production)
              echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROD_PROJECT_ID }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown environment: ${{ github.event.inputs.environment }}"
              exit 1
              ;;
          esac
      
      - name: Determine Vercel Environment
        run: |
          if [ "${{ github.event.inputs.is_preview }}" == "true" ]; then
            vercel_env="preview"
            vercel_build_flag=""
            vercel_deploy_flag=""
          else
            vercel_env="production"
            vercel_build_flag="--prod"
            vercel_deploy_flag="--prod"
          fi
          echo "VERCEL_JOB_ENV=$vercel_env" >> $GITHUB_ENV
          echo "VERCEL_BUILD_FLAG=$vercel_build_flag" >> $GITHUB_ENV
          echo "VERCEL_DEPLOY_FLAG=$vercel_deploy_flag" >> $GITHUB_ENV

      - name: Pull Vercel Environment
        run: npx vercel pull --yes --environment=$VERCEL_JOB_ENV --token=$VERCEL_TOKEN

      - name: Build Project Artifacts
        run: npx vercel build $VERCEL_BUILD_FLAG --token=$VERCEL_TOKEN

      - name: Deploy to Vercel
        run: npx vercel deploy $VERCEL_DEPLOY_FLAG --prebuilt --token=$VERCEL_TOKEN