name: Trigger Vercel Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        type: choice
        options:
          - Development
          - Staging
          - Production
        default: Development
      is_preview:
        description: "Create a preview"
        required: true
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }} ${{ github.event.inputs.is_preview == 'true' && '(Preview)' || '' }}
  cancel-in-progress: false

jobs:
  Trigger-Deployment:
    name: Deploy to ${{ github.event.inputs.environment }} ${{ github.event.inputs.is_preview == 'true' && '(Preview)' || '' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.is_preview == 'false' && github.event.inputs.environment || null }}
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_TEAM: ${{ vars.VERCEL_TEAM }}
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Downloads also the tags
          ref: ${{ github.ref }}

      - name: Set Vercel Project ID
        run: |
          case "${{ github.event.inputs.environment }}" in
            Development)
              echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_DEV_PROJECT_ID }}" >> $GITHUB_ENV
              ;;
            Staging)
              echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_STAGING_PROJECT_ID }}" >> $GITHUB_ENV
              ;;
            Production)
              echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROD_PROJECT_ID }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown environment: ${{ github.event.inputs.environment }}"
              exit 1
              ;;
          esac

      - name: Determine Deployment Flag
        run: |
          if [ "${{ github.event.inputs.is_preview }}" == "true" ]; then
            vercel_deploy_flag=""
          else
            vercel_deploy_flag="--prod"
          fi
          echo "VERCEL_DEPLOY_FLAG=$vercel_deploy_flag" >> $GITHUB_ENV

      - name: Deploy to Vercel
        # run: npx vercel deploy --scope $VERCEL_TEAM $VERCEL_DEPLOY_FLAG --token=$VERCEL_TOKEN
        run: npx vercel deploy $VERCEL_DEPLOY_FLAG --token=$VERCEL_TOKEN