name: Trigger Workflow Manually

on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: "Select a workflow to trigger"
        required: true
        type: choice
        options:
          - deploy-preview-development.yml
          - deploy-development.yml
          - deploy-staging.yml
          - deploy-production.yml

permissions:
  actions: write         # For dispatching workflows

jobs:
  Call-Reusable-Workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call the Reusable Workflow
        uses: ./.github/workflows/${{ inputs.workflow_name }}
        with:
          ref: ${{ github.ref }}